### ISSUE TITLE
Goto function to move forward and back in time

### ISSUE THREAD

**Issue by dfalster** [ropenscilabs/ozrepro#10]
Seamless of moving forward and back in history

**Comment by smwindecker** [comment]
rollback() ?
rollforward()
go_to()

retrieve()

the roll functions will just let you look at different points, the retrieve function will go back to a particular point and make it the new head (equivalent of checkout, branch, commit).

**Comment by goldingn** [comment]
`go_to()` works pretty smoothly now, you can just punch in an integer and go to that commit. `record()` and even works when back in time. I'm not sure we need specific forward and back functions like `go_back()` and `go_forward()`, since `go_to()` is more explicit.

I vote to close this, does anyone object?

**Comment by dfalster** [comment]
Agreed

**Comment by dfalster** [comment]
I love the use of integers for referencing commits. But I should we also support a sha? I'm thinking of the case where new user is interacting with experienced user. Being able to use eithjer an integer or a sha seems like a plus to me.

**Comment by goldingn** [comment]
Yeah, good point, we should add the option to `go_to()`.

I removed the shas from `print.timeline()` as I thought they might by confusing for novice users (and visual clutter).  We could always add an option to `timeline()` to include that info, and make `print.timeline()` respect that, so it's something like this?:

```r
timeline()
```
```
      (1) initial commit
       |  2017-10-30 02:43
       |
      (2) set up project structure
       |  2017-10-30 02:43
       |
      (3) added stuff to readme
          2017-10-30 02:43
```

```r
timeline(include_sha = TRUE)
```
```
      (1) initial commit [6019af6]
       |  2017-10-30 02:43
       |
      (2) set up project structure [7a39893]
       |  2017-10-30 02:43
       |
      (3) added stuff to readme [34db189]
          2017-10-30 02:43
```

similarly we could add an `include_author` argument
