### ISSUE TITLE
Adding the "cache"

### ISSUE THREAD

**Issue by smbache** [ropenscilabs/ozrepro#14]
- [x] checkRepo function 
- [x] get_repo() decision and possibly implementation.
- [x] .cache environment
- [x] ready function: does it exist? 
- [ ] ...

**Comment by timchurches** [comment]
Unable to get this to work:

```
> devtools::load_all()
Loading stow
> stow::get_repo()
Error in discover_repository(cwd) : 
  could not find function "discover_repository"
> library(git2r)
> stow::get_repo()
> stow::ready()
Error in some(cache$repo) : object 'cache' not found
```

**Comment by goldingn** [comment]
ready() shouldn't be exported, it's just some of the remnant prototype code
that we can remove soon.

**Comment by smbache** [comment]
1) `discover_repository` is a `git2r` function and is imported by `stow`, it won't show up by `load(ing)_all`. 

2) it should be `.cache` and not `cache`.

**Comment by goldingn** [comment]
It looks like the cache stuff is working as expected - there are just a bunch of unexported prototype functions that don't work with it. I'll close this again, and we can focus on exporting the right functions next!
