### ISSUE TITLE
Creating a repo (new and existing)

### ISSUE THREAD

**Issue by dfalster** [ropenscilabs/ozrepro#2]
Need two functions -- one which clones a repo from existing online source and another which creates a new repo.

Suggested structures are as follows:

```
download_repo(remote="git@...")
```
Downloads an existing git repo from specified (existing remote) -- e.g. `github.com:ropenscilabs/ozrepro.git`

Alternative names for `download` are `clone` and `fetch`. 

And
```
create_repo(path = getwd(), create_structure =TRUE)
```
initliases an entirely new repo at the specified path, with default the current working directory.
The `create_structure` argument determines whether we add some default structure to the project, including

- file `.gitignore` (and basic ignores
- `X.Rproj` (Rstudio project file)
- folders `R`, `data`,  `output` and `ignore`  (and in each a basic readme)

Alternative names for `create` are `initialise` and `start`.

**Comment by dfalster** [comment]
create_repo has been implemented. 

Need to implement `download_repo`

**Comment by goldingn** [comment]
Awesome.

We've been avoiding the term repo in the rest of the docs, vignettes and messages and using 'project' (for the user's code) and 'version control project' (for the git repo).

We should consider whether to rename these accordingly.

**Comment by dvukcevic** [comment]
During the unconf I believe the only git terminology we were using was 'repository', but I agree we can change that to 'project' which would be more familiar to beginners, so I support renaming these functions.
