### ISSUE TITLE
Make website for package

### ISSUE THREAD

**Issue by dvukcevic** [ropenscilabs/ozrepro#35]
I propose we use [pkgdown](http://hadley.github.io/pkgdown) to easily make a nice website, and put the main documentation on it.

**Comment by dvukcevic** [comment]
The pkgdown website has a [get started](https://hadley.github.io/pkgdown/articles/pkgdown.html) page.  I also found [blog post](https://lbusettspatialr.blogspot.com.au/2017/08/building-website-with-pkgdown-short.html).

**Comment by dvukcevic** [comment]
See pull request #53

**Comment by goldingn** [comment]
done & done!
