### ISSUE TITLE
Functions for taking a snapshot that commit existing structure

### ISSUE THREAD

**Issue by dfalster** [ropenscilabs/ozrepro#6]
Suggested structures are as follows:

```
record()
```
Could also call to a specific file?

```
record("file.R")
```
Alternative names for `stage` or `commit`?

**Comment by goldingn** [comment]
`record()` now works pretty smoothly, but can't handle specific files.

A nice syntax for that would be:

```r
record("did stuff", only = "file.R")
```
or
```r
record("did other stuff", not = "other_file.R")
```
with both defaulting to NULL (commit everything)
