### ISSUE TITLE
Why require the user to cut and paste or type a SHA?

### ISSUE THREAD

**Issue by timchurches** [ropenscilabs/ozrepro#61]
https://github.com/ropenscilabs/ozrepro/blob/0d1b9b3913e9425071a337573149032d6e1addad/R/go_to.R#L11

To check out a commit that was n commits ago you can just use  git checkout branch-name@{n}

That way the user only needs to specify how far they wish to go back, and doesn’t have to fuss with SHAs at all. Or am I overlooking something that makes the need to specify a SHA essential?

I think the same may apply to the revert() function? Much better if the user can just specify an integer index of how far back the wish to go.

**Comment by smbache** [comment]
They definitely should not be bothered with shas - it was just the fastest thing to do to get it working, and with the time limit of few minutes at the end we didn’t come up with what the better way should be. 

But you’re 100% right.

**Comment by smbache** [comment]
Saras had some integer ids exposed in the history - maybe they could be the input

**Comment by timchurches** [comment]
go_to() and retrieve() could possibly accept either an integer or a SHA as its argument. It is easy for the function to work out which of those two types of values has been passed and behave accordingly.

**Comment by timchurches** [comment]
Yes, I think the integer indices in Saras’ timeline() - I still think it should be called herstory(), btw, or at least be given an alias of herstory() - should be zero-based (the HEAD is index 0), so that the index can be passed directly to go_to() and retrieve(). We were discussing a Shiny app based around a table of the timeline/herstory, displayed using the DT htmlwidget (which is a wrapped jQuery Datatable that would allow users to search commit messages etc).

**Comment by dfalster** [comment]
Great suggestions Tim!

**Comment by smwindecker** [comment]
Can definitley change the indexing to start at zero. And yes I think the shiny widget would be great. At the start it could simply allow you to scroll and search through the timeline, but eventually when the other functions are working you could click on an entry and then either go_to it or retrieve it from there.
