### ISSUE TITLE
render a file diff

### ISSUE THREAD

**Issue by goldingn** [ropenscilabs/ozrepro#64]
currently, running `changes()` on a file just repeats the same minimal information about line changes as when running it for the whole repo. Ideally, it would give the user a diff for that file.

`git2r` does return diffs for each file, but they're in some obscure format and it doesn't have a way of rendering them. It looks like that's something we'll have to do.

**Comment by smwindecker** [comment]
Note: this was mentioned again when changes was presented at QAECO.
