### ISSUE TITLE
make sure git is available

### ISSUE THREAD

**Issue by goldingn** [ropenscilabs/ozrepro#65]
We need to make sure git is available for the package to use.

I think git2r includes the libgit2 source, so should be standalone (though we'd need to check this).
However the current code makes a number of system calls to git, which will only work if git is installed and visible at the command line. 

We could either automate installation of command line git or (preferably) implement the functionality we need in git2r and remove the system calls.

**Comment by dfalster** [comment]
Agreed. Relying solely on git2r is preferable, as we can avoid installation issues. Might need to extend git2r to get all the functionality we want.

**Comment by smwindecker** [comment]
Boosting this issue as was mentioned in the QAECO presentation of changes.
